name: Publish Python Package to PyPI
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: { python-version: "3.10" }
    - run: python3 -m pip install build --user
    - run: python3 -m build
    - uses: actions/upload-artifact@v7
      with:
        name: python-package-distributions
        path: dist/
  publish-to-pypi:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - uses: pypa/gh-action-pypi-publish@release/v1
